---
- hosts: aws_servers
  become: yes
  tasks: 
  - name: i want to install git
    yum:
      name: git
      state: present 
  - name: i want to install tree
    yum:
      name: tree
      state: present
  - name: i want to install wget
    yum:
      name: httpd
      state: present
  